branches:
  only:
  - master
language: python
python:
- 2.7
install:
- pip install -r requirements.txt
script:
- make html
notifications:
  email:
    on_success: false 
    on_failure: always
env:
  global:
  - secure: EuleRVAaoed/C7mn6swpagRyfCf/ffhvavamXpqAx2KnbnAY1HX9sRFO8E2zCnjLLLz6ShgoWSNA4cloFnCbX41XbOnPXuUJkyBrV61X4twvVOcoDw/w2KVZfyhJ9umU5Ci4rr8kkGgIw8RPu8hFXP/0vVCk/I43t2K0KDshXrs=
  - secure: ZWF4INWwDIwH1ZUUPFjqH5jezJ2F5cufM4e5tUfbfD8L8t8MdSdFegFgexyEz7UZ9lKyo0F3z4eLs31WfrDcjhxj6NIUuvyJa6am4HtE4sIR+ewy7gNcFsJN/so9A5I8DhltvqjC65gYV/1T1zuA/QDrckfCf9Kvfn4E7LzfYds=
before_install:
- git submodule update --init --recursive
after_success: bash deploy.sh
